//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pratz
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyTable
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> NoteId { get; set; }
    
        public virtual Note Note { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
